CREATE OR REPLACE TYPE NATURESLEEP."OBJ_4240" FORCE                                                                                                                                                                                                                                                                                                             
AS object 
(
  Status              VARCHAR2(10 CHAR),
  ordNo               VARCHAR2(20 CHAR),
  ordNoOrg            VARCHAR2(20 CHAR),
  ordDate             VARCHAR2(14 CHAR),
  accDate             VARCHAR2(14 CHAR),
  canDate             VARCHAR2(14 CHAR),
  cntNameOrd          VARCHAR2(45 CHAR),
  Userid              VARCHAR2(10 CHAR),
  Username            VARCHAR2(45 CHAR),
  userKindName        VARCHAR2(30 CHAR),
  cntNameMem          VARCHAR2(45 CHAR),
  grpName             VARCHAR2(45 CHAR),
  rId                 VARCHAR2(10 CHAR),
  rName               VARCHAR2(60 CHAR),
  omniYN              VARCHAR2(10 CHAR),
  countryName         VARCHAR2(45 CHAR),
  kindName            VARCHAR2(30 CHAR),
  pathName            VARCHAR2(30 CHAR),  
  cateCD              VARCHAR2(5 CHAR),
  cateName            VARCHAR2(45 CHAR),
  pdtCD               VARCHAR2(10 CHAR),
  pdtName             VARCHAR2(90 CHAR),
  Barcode             VARCHAR2(20 CHAR),
  pdtStatus           VARCHAR2(30 CHAR),
  bOMYN               VARCHAR2(10 CHAR),
  packageYN           VARCHAR2(10 CHAR),
  pdtKind             VARCHAR2(20 CHAR),
  pdtOption           VARCHAR2(90 CHAR),
  option1             VARCHAR2(200 CHAR),
  option2             VARCHAR2(200 CHAR),
  option3             VARCHAR2(200 CHAR),  
  Price               NUMBER,
  VAT                 NUMBER,
  Amt                 NUMBER,
  Pv1                 NUMBER,
  Pv2                 NUMBER,
  Pv3                 NUMBER,
  Point               NUMBER,
  Qty                 NUMBER,
  SumPrice            NUMBER,
  SumVAT              NUMBER,
  SumAmt              NUMBER,
  SumPv1              NUMBER,
  SumPv2              NUMBER,
  SumPv3              NUMBER,
  SumPoint            NUMBER,
  QtyPP               NUMBER,
  QtyStk              NUMBER,    
  PdtIOKind           VARCHAR2(10 CHAR),
  SerailNo            VARCHAR2(20 CHAR),
  Remark              VARCHAR2(90 CHAR),
  WorkDate            DATE,
  WorkUser            VARCHAR2(10 CHAR),  
  recName             VARCHAR2(60 CHAR),
  rMobile             VARCHAR2(20 CHAR),
  rPost               VARCHAR2(250 CHAR),
  rAddr1              VARCHAR2(250 CHAR),
  rTel                VARCHAR2(20 CHAR),
  rMemo               VARCHAR2(180 CHAR)
);
/