    //--5030-- 출고지시 조회 - Truy vấn chỉ thị xuất kho                                                                                 
	@Query(value =
			 "SELECT A.Ord_NO || '-' || A.Deli_Seq AS Deli_NO                                                                     "        
			+"     , ufDate(:lang, 'L', A.Send_Date) AS Send_Date                                                                 "
			+"     , A.Deli_Seq                                                                                                   "
			+"     , A.Send_User                                                                                                  "
			+"     , ufName(A.Com_ID,'SM_USER',A.Send_User) AS Send_User_Name                                                     "
			+"     , ufName(A.Com_ID,'CENTER',A.Store_CD) AS Store_Name                                                           "
			+"     , ufName(A.Com_ID,'CENTER',A.Courier_CD) AS Courier_Name                                                       "
			+"     , ufName(D.Com_ID,'DELI_KIND',A.Deli_Kind) AS Deli_Kind                                                        "
			+"     , D.Userid                                                                                                     "
			+"     , D.Username                                                                                                   "
			+"     , ufName(A.Com_ID,'CENTER',D.Cnt_CD) AS CNT_Name                                                               "
			+"     , B.Pdt_CD                                                                                                     "
			+"     , ufName(A.Com_ID,'PRODUCT',B.Pdt_CD) AS Pdt_Name                                                              "
			+"     , DECODE(C.STATUS, 'R', '-' || B.Qty, B.Qty)    AS Qty                                                         "
			+"     , C.Ord_NO                                                                                                     "
			+"     , ufDate(:lang, 'L', C.Ord_Date) AS Ord_date                                                                   "
			+"     , ufName(D.Com_ID,'ORD_MST.STATUS',C.Status) AS Status                                                         "
			+"     , ufName(A.Com_ID,'CODE',C.Kind_CD) AS Kind_Name                                                               "
			+"     , ufName(A.Com_ID,'CODE',C.Path_CD) AS Path_Name                                                               "
			+"     , ufName(A.Com_ID,'ORD_MST.RCPT_YN',C.Rcpt_YN) AS Rcpt_YN                                                      "
			+"     , A.R_Name                                                                                                     "
			+"     , A.R_Tel                                                                                                      "
			+"     , A.R_Mobile                                                                                                   "
			+"     , A.R_Post                                                                                                     "
			+"     , A.R_Addr1 || ' ' || A.R_Addr2 AS R_Addr                                                                      "
			+"     , A.R_Memo                                                                                                     "
			+"     , A.Remark                                                                                                     "
			+"     , D.Username_Kana AS mUseKana                                                                                  "
			+"     , ufUsername_English(D.Given_Name, D.Middle_Name, D.Family_Name) AS mUseEnglish                                "
			+"  FROM Ord_Deli A                                                                                                   "
			+"     , Ord_Deli_Pdt B                                                                                               "
			+"     , Ord_Mst C                                                                                                    "
			+"     , Member D                                                                                                     "
			+" WHERE A.Ord_NO     = B.Ord_NO                                                                                      "
			+"   AND A.Ord_NO     = C.Ord_NO                                                                                      "
			+"   AND A.Userid     = D.Userid                                                                                      "
			+"   AND A.Com_ID    = :comId                                                                                         "
			+"   AND A.Send_Date BETWEEN  NVL(:orderDateStart, '00000000') AND NVL(:orderDateEnd, '99999999')                     "
			+"   AND A.Send_Date IS NOT NULL                                                                                      "
			+"   AND A.Deli_Seq            LIKE NVL(:deliSeq, '%')                                                                "
			+"   AND B.Deli_Seq            LIKE NVL(:deliSeq, '%')                                                                "
			+"   AND NVL(A.Store_CD,'-')   LIKE NVL(:storedCd, '%')                                                               "
			+"   AND NVL(A.Courier_CD,'-') LIKE NVL(:courierCd, '%')                                                              "
			+"   AND A.Deli_Kind           LIKE NVL(:deliKind, '%')                                                               "
			+"   AND B.Pdt_CD              LIKE NVL(:pdtCd, '%')                                                                  "
			+"   AND ((:valueSel = 0 AND A.Deli_Seq        LIKE NVL(:value, '%'))                                                 "
			+"      OR (:valueSel = 1 AND A.Ord_NO          LIKE NVL(:value, '%'))                                                "
			+"      OR (:valueSel = 2 AND NVL(A.R_Name,'-') LIKE NVL(:value, '%'))                                                "
			+"      OR (:valueSel = 3 AND (NVL(A.R_Tel,'-') LIKE NVL(:value, '%') OR NVL(A.R_Mobile,'-') LIKE NVL(:value, '%')))) "
			+"   AND A.Userid IN (SELECT Userid FROM Table(ufTBL_USERID(:chkuserId, :userid, :cntCd)))                            "
			+" ORDER BY A.Send_Date, A.Ord_NO, A.Deli_Seq                                                                         "
			, nativeQuery = true)                                  
	public List<OrdDeliModel> findDeliInstructionCheck(String comId, String lang, String orderDateStart, String orderDateEnd, String deliSeq, 
			String storedCd, String courierCd, String deliKind, String userid, String pdtCd, String valueSel, String value, int chkuserId, 
			String cntCd, Pageable pageable);
			
			
			//--5030-- 출고지시 조회 - Truy vấn chỉ thị xuất kho  
	@Query(value =
			 " SELECT Com_ID                                                                                           "
	  		+"      , Pdt_CD                                                                                           "
	  		+"      , Pdt_Name                                                                                         "
	  		+"      , Sum(Pick_Qty) AS Qty                                                                             "
	  		+"   FROM (SELECT A.Com_ID                                                                                 "
	  		+"              , A.Pdt_CD                                                                                 "
	  		+"              , C.Pdt_Name                                                                               "
	  		+"              , (A.Qty) AS Pick_Qty                                                                      "
	  		+"           FROM Ord_Deli_Pdt A                                                                           "
	  		+"              , Ord_Deli B                                                                               "
	  		+"              , Pdt_Mst  C                                                                               "
	  		+"              , Ord_Mst  D                                                                               "
	  		+"          WHERE A.Com_Id = :comId                                                                        "
	  		+"            AND A.Ord_NO   = B.Ord_NO                                                                    "
	  		+"            AND A.Deli_Seq = B.Deli_Seq                                                                  "
	  		+"            AND A.Pdt_CD   = C.Pdt_CD                                                                    "
	  		+"            AND B.Ord_NO   = D.Ord_NO                                                                    "
	  	    +"            AND B.Send_Date BETWEEN NVL(:orderDateStart, '00000000') AND NVL(:orderDateEnd, '999999999') "
	  	    +"            AND B.Send_Date IS NOT NULL                                                                  "
		    +"            AND NVL(A.Release_NO,'-') LIKE NVL(:deliSeq, '%')                                            "
		    +"            AND NVL(B.Store_CD,'-')   LIKE NVL(:storedCd, '%')                                           "
		    +"            AND NVL(B.Courier_CD,'-') LIKE NVL(:courierCd, '%')                                          "
	  		+"            AND B.Deli_Kind           LIKE NVL(:deliKind, '%')                                           "
	  		+"            AND C.BOM_YN     = 'N'                                                                       "
	  		+"         UNION ALL                                                                                       "
	  		+"         SELECT A.Com_ID                                                                                 "
	  		+"              , E.Comp_CD AS Pdt_CD                                                                      "
	  		+"              , F.Pdt_Name                                                                               "
	  		+"              , (A.Qty*E.Qty) AS Pick_Qty                                                                "
	  		+"           FROM Ord_Deli_Pdt A                                                                           "
	  		+"              , Ord_Deli B                                                                               "
	  		+"              , Pdt_Mst  C                                                                               "
	  		+"              , Ord_Mst  D                                                                               "
	  		+"              , Pdt_Bom  E                                                                               "
	  		+"              , Pdt_Mst  F                                                                               "
	  		+"          WHERE A.Com_Id = :comId                                                                        "
	  		+"            AND A.Ord_NO   = B.Ord_NO                                                                    "
	  		+"            AND A.Deli_Seq = B.Deli_Seq                                                                  "
	  		+"            AND A.Pdt_CD   = C.Pdt_CD                                                                    "
	  		+"            AND B.Ord_NO   = D.Ord_NO                                                                    "
	  		+"            AND C.Pdt_CD   = E.Pdt_CD                                                                    "
	  		+"            AND E.Comp_CD  = F.Pdt_CD                                                                    "
	  		+"            AND C.BOM_YN   = 'Y'                                                                         "
	  	    +"            AND B.Send_Date BETWEEN NVL(:orderDateStart, '00000000') AND NVL(:orderDateEnd, '99999999')  "
	  	    +"            AND B.Send_Date IS NOT NULL                                                                  "
		    +"            AND NVL(A.Release_NO,'-') LIKE NVL(:deliSeq, '%')                                            "
		    +"            AND NVL(B.Store_CD,'-')   LIKE NVL(:storedCd, '%')                                           "
		    +"            AND NVL(B.Courier_CD,'-') LIKE NVL(:courierCd, '%')                                          "
	  		+"            AND B.Deli_Kind           LIKE NVL(:deliKind, '%')) X                                        "
	  		+"  GROUP BY Com_ID, Pdt_CD, Pdt_Name                                                                      "
			, nativeQuery=true)                                         
  	public List<OrdDeliPdtModel> findDeliPdtInstructionCheck(String comId, String orderDateStart, String orderDateEnd, 
  			String deliSeq, String storedCd, String courierCd, String deliKind, Pageable pageable);